### ISSUE TITLE
会不会出现卡死重启的情况

### ISSUE THREAD

**Issue by MellongLau** [ParkinWu/EFI-B360-AORUS-PRO-HUD630-8700#1]
Hi @ParkinWu ， 我用你给的 EFI 可以驱动，但是发现时不时会卡死（鼠标可以动，鼠标旁边有风火轮在转，然后点击无反应，几秒后就自动重启），还有有时候睡眠会自己唤醒。

**Comment by ParkinWu** [comment]
@MellongLau 我用了近半个月了，没有出现过任何异常，你装的是10.14.5吧，我这EFI是10.14.5才行

**Comment by MellongLau** [comment]
是啊，用的就是10.14.5，时不时会卡死重启。。。

**Comment by ParkinWu** [comment]
@MellongLau 硬盘型号呢？

**Comment by ParkinWu** [comment]
970 EVO Plus 和 三星 PM981 这两个型号的硬盘装黑苹果似乎是会死机

**Comment by MellongLau** [comment]
硬盘我用的是西部数据的 sn750 黑盘 m2 nvme 1T的

**Comment by ParkinWu** [comment]
@MellongLau 那我也不清楚了，除了这个问题，其他驱动都OK了吗

**Comment by MellongLau** [comment]
是啊，其他都没什么问题，我加了 wifi 和蓝牙也都 work。

**Comment by MellongLau** [comment]
昨晚更新了bios到F3，今天突然间发现不卡死重启了，一切正常。

**Comment by ParkinWu** [comment]
@MellongLau 好的，那issue关了

**Comment by MellongLau** [comment]
Thanks
